<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>Jumbotron Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <!-- Latest compiled and minified CSS
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css"> -->
    <!-- Custom styles for this template
    <link href="http://d15w24j4jq6e4n.cloudfront.net/css/jumbotron.css" rel="stylesheet"> -->
    <style>
        body {
            padding-top: 50px;
            padding-bottom: 20px;
        }
    </style>

        <!-- Bootstrap core JavaScript
    ================================================== -->
    <?php
        echo $this->HeadLink()->appendStylesheet("//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css");

        echo $this->HeadScript()->appendFile("https://code.jquery.com/jquery-1.10.2.min.js", $type = 'text/javascript')
                                ->appendFile("//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js", $type = 'text/javascript');
    ?>
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- Latest compiled and minified JavaScript -->

  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" role="form">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </div>



    <div class="container">

    <?php echo $this->content; ?>

    </div> <!-- /container -->

  </body>
</html>
